#!/usr/bin/env python

Import('env')
Import('env_modules')

env_skeleton_fit = env_modules.Clone()

env_skeleton_fit.Prepend(CPPPATH=['.'])
env_skeleton_fit.Prepend(CPPPATH=['thirdparty/Eigen'])
env_skeleton_fit.Prepend(CPPPATH=['thirdparty/kiwi'])
env_skeleton_fit.Prepend(CPPPATH=['thirdparty/dynamic-means/src'])
env_thirdparty = env_skeleton_fit.Clone()

# env_thirdparty.disable_warnings()
# env_thirdparty.add_source_files(env.modules_sources, "src/*.cpp")

env_skeleton_fit.add_source_files(env.modules_sources, "*.cpp")